### ISSUE TITLE
Typo - SingUpDto.hpp

### ISSUE THREAD

**Issue by JerrySB03** [oatpp/example-jwt#4]
The file /src/dto/SingUpDto.hpp should be called /src/dto/SignUpDto.hpp.

**Comment by lganzzzo** [comment]
Hello @JerrySB03 ,

Thanks for the issue!
Please feel free to create a PR

Regards,
Leonid

**Comment by JerrySB03** [comment]
Issue fixed with PR #5

**Comment by JerrySB03** [comment]
Issue fixed with PR #5
